INSERT INTO ngos (name, latitude, longitude, address, contact_info) VALUES ('Paws and Claws', 19.0760, 72.8777, '123 MG Road, Mumbai', 'contact@pawsandclaws.in');
INSERT INTO ngos (name, latitude, longitude, address, contact_info) VALUES ('Pet Centre', 28.6139, 77.2090, '456 Connaught Place, Delhi', 'hello@petcentre.in');
INSERT INTO ngos (name, latitude, longitude, address, contact_info) VALUES ('Petify', 12.9716, 77.5946, '789 Residency Road, Bengaluru', 'support@petify.in');

INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Max', 'Golden Retriever', 3, 'Friendly and active.', 'AVAILABLE', 'https://images.unsplash.com/photo-1633722715463-d30f4f325e24?w=600&h=400&fit=crop', 'Fully Vaccinated', 'None', 0, 1);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Luna', 'Persian Cat', 2, 'Loves to sleep.', 'AVAILABLE', 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=400&fit=crop', 'Fully Vaccinated', 'Minor Allergies', 0, 1);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Charlie', 'Beagle', 1, 'Full of energy!', 'AVAILABLE', 'https://images.unsplash.com/photo-1505628346881-b72b27e84530?w=600&h=400&fit=crop', 'Needs booster', 'None', 0, 2);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Bella', 'German Shepherd', 4, 'Protective.', 'AVAILABLE', 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=600&h=400&fit=crop', 'Fully Vaccinated', 'None', 0, 2);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Milo', 'Labrador', 2, 'Gentle giant.', 'AVAILABLE', 'https://images.unsplash.com/photo-1529429617124-95b109e86bb8?w=600&h=400&fit=crop', 'Partially Vaccinated', 'None', 0, 3);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Rocky', 'Siberian Husky', 2, 'Loves snow and running.', 'AVAILABLE', 'https://images.unsplash.com/photo-1605568420116-b118b6287b4e?w=600&h=400&fit=crop', 'Fully Vaccinated', 'None', 0, 3);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Daisy', 'Bulldog', 3, 'Lazy but loving.', 'AVAILABLE', 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=600&h=400&fit=crop', 'Fully Vaccinated', 'Mild Arthritis', 0, 1);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Simba', 'Poodle', 1, 'Very playful.', 'AVAILABLE', 'https://images.unsplash.com/photo-1591160690555-5debfba289f0?w=600&h=400&fit=crop', 'Fully Vaccinated', 'None', 0, 2);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Nala', 'Maine Coon', 4, 'Majestic and calm.', 'AVAILABLE', 'https://images.unsplash.com/photo-1513245543132-31f507417b26?w=600&h=400&fit=crop', 'Fully Vaccinated', 'None', 0, 1);
INSERT INTO pets (name, breed, age, description, status, image_url, vaccination_status, disease, version, ngo_id) VALUES ('Coco', 'Parrot', 2, 'Smart and talkative.', 'AVAILABLE', 'https://images.unsplash.com/photo-1552728089-57105a88c3a1?w=600&h=400&fit=crop', 'Fully Vaccinated', 'None', 0, 3);
